# Ansible playbook to install docker
# Base instructions can be found at
# https://docs.docker.com/engine/install/centos/
- name: Install minikube
  hosts: local
  become: yes
  become_method: sudo
  tasks:
    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present
    - name: Add docker yum repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0664'
    - name: Install docker engine
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: Ensure OS group docker exists
      group:
        name: docker
        state: present
    - name: Ensure SUDO_USER is part of the docker OS group
      user:
        name: "{{ SUDO_USER }}"
        groups: docker
        append: yes
    - name: Start docker service
      systemd:
        name: docker
        state: started