# Ansible playbook for installing zookeeper and kafka
- name: Install minikube
  hosts: local
  tasks:
    - name: Create a k8s namespace
      community.kubernetes.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present